---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - temporal.simonemms.com
  resources:
  - connections
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - temporal.simonemms.com
  resources:
  - connections/status
  - namespaces/status
  - searchattributes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - temporal.simonemms.com
  resources:
  - namespaces
  - searchattributes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - temporal.simonemms.com
  resources:
  - namespaces/finalizers
  - searchattributes/finalizers
  verbs:
  - update
