## Append samples of your project ##
resources:
- temporal_v1beta1_connection.yaml
- temporal_v1beta1_namespace.yaml
- temporal_v1beta1_searchattribute.yaml
- temporal_v1beta1_nexusendpoint.yaml
- temporal_v1beta1_schedule.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
