## Append samples of your project ##
resources:
- temporal_v1alpha1_connection.yaml
- temporal_v1alpha1_namespace.yaml
- temporal_v1alpha1_searchattribute.yaml
- temporal_v1alpha1_nexusendpoint.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
